### ISSUE TITLE
Classpath for GWT compiler is set incorrectly if using a Project-to-project dependency instead of a multi-project setup

### ISSUE THREAD

**Issue by centic9** [steffenschaefer/gwt-gradle-plugin#81]
I have a simple two-project setup where one project is including a shared project, both contain GWT code. I sculptured the build similar to the examples for "library" and "war-using-library", the only difference being that we do not use a multi-project setup with a global build.gradle/settings.gradle, but just link from the main project to the shared project via a settings.gradle and project-dependencies.

When adding GWT code to the shared project, we see the following error 

```
:compileGwt
Loading inherited module 'de.richsource.gradle.plugins.gwt.example.Example'
   Loading inherited module 'de.richsource.gradle.plugins.gwt.example.library.Library'
      [ERROR] Unable to find 'de/richsource/gradle/plugins/gwt/example/library/Library.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
:compileGwt FAILED
```

Investigating some more showed that the suggested way of adding sources via 

```
	println 'sourceSet: ' + project(':example-library').sourceSets.main.allJava.srcDirs
	src += files(project(':example-library').sourceSets.main.allJava.srcDirs) + files(project(':example-library').sourceSets.main.output.resourcesDir)
```

does not work in this case, i.e. it prints:

```
sourceSet: [C:\temp\examples\war-using-library\src\main\java]
```

which means the project('...') stuff above does not work in our setup

We solved it via adding 
````
src += files('../library/src/main/java')
```

instead.

Not sure if it is some problem with the GWT plugin or a general Gradle behavior, at least the documentation could note this

**Comment by centic9** [comment]
I have uploaded a sample-repository which allows to reproduce this problem at https://github.com/centic9/gwt-gradle-example-issue81

**Comment by rbrindl** [comment]
Hi, I have just tried your example and experienced the same. 
But I do not think this is an issue with this plugin. I removed all the GWT specific stuff from the projects. Whats left are just to plain java projects. I get the same results.

The reason for this is that the root project is evaluated first. It accesses the child projects which have not been evaluated yet and their entries for sourcesets are still at their defaults.

To avoid this you could either:
* wrap your `gwt{...}` section with `gradle.projectsEvaluated { ... }` 
* wrap your `gwt{...}` section with `project(':example-library').afterEvaluate{...}`  (be aware that the default delegate inside the closure is the example-library project object)
* add `evaluationDependsOn(':example-library')`

I would prefer the first solution, because it has less influence on the rest of your project structure.

I suggest to close this issue because it is not an issue with this plugin, it is a principal gradle behavior

**Comment by centic9** [comment]
Hi, 

thanks for the analysis and the hints, that seems to work! Gradle/Groovy still confuses me sometimes :)
